---
- name: Crear usuario de servicio para Ansible
  hosts: Rocky
  become: true
  
  vars:
    admin_public_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

  tasks:
    - name: 1. Crear usuario servicio ansible
      ansible.builtin.user:
        name: ansible
        comment: "Usuario de servicio ansible"
        shell: /sbin/nologin                                                # Deshabilita el login
        system: true                                                        # Crea un usuario de sistema
        create_home: true                                                   # Crea el home del usuario
        state: present

    - name: 2. Permisos sudo sin contraseña para usuario ansible
      ansible.builtin.copy:
        dest: /etc/sudoers.d/ansible                                        
        content: "ansible ALL=(ALL) NOPASSWD: ALL"                          
        owner: root
        group: root
        mode: '0440'
        validate: /usr/sbin/visudo -csf %s                                  # Valida la sintaxis del archivo antes de guardar

    - name: 3. Guardar clave ssh en authorized_keys
      ansible.posix.authorized_key:
        user: ansible
        state: present
        key: "{{ admin_public_key }}"
