---
- name: Crear usuario de servicio para Ansible
  hosts: Centos-9
  become: true

  tasks:

    - name: Buscar clave pública
      delegate_to: localhost
      run_once: true
      become: false
      ansible.builtin.find:
        paths: "~/.ssh"
        patterns: "id*.pub"
      register: key_publica

    - name: Fallar si no se encuentra ninguna clave pública
      delegate_to: localhost
      run_once: true
      ansible.builtin.fail:
        msg: "Error - Sin clave publica en ~/.ssh/. Para generar una usar ssh-keygen."
      when: key_publica.files | length == 0

    - name: Crear usuario servicio ansible
      ansible.builtin.user:
        name: ansible
        comment: "Usuario de servicio ansible"
        # shell: /bin/bash                                                    # Deshabilita el login
        system: true                                                        # Crea un usuario de sistema
        create_home: true                                                   # Crea el home del usuario
        umask: '022'
        state: present

    - name: Permisos sudo sin contraseña para usuario ansible
      ansible.builtin.copy:
        dest: /etc/sudoers.d/ansible
        content: "ansible ALL=(ALL) NOPASSWD: ALL"
        owner: root
        group: root
        mode: '0440'
        validate: /usr/sbin/visudo -csf %s                                  # Valida la sintaxis del archivo antes de guardar

    - name: Guardar clave ssh en authorized_keys
      ansible.posix.authorized_key:
        user: ansible
        state: present
        key: "{{ lookup('file', key_publica.files[0].path) }}"


